// Sample approved OTC inventory. Replace with the real uploaded inventory.
const INVENTORY = [
  {
    name: "Acetaminophen 500mg Tablets",
    icon: "💊",
    symptoms: ["headache", "fever", "pain", "sore throat", "body ache"],
    directions: "Take 2 tablets every 6 hours as needed.",
    dosage: "Max 6 tablets (3000mg) per 24 hours.",
    warnings: "Do not use with other acetaminophen products. Liver risk if exceeded.",
    ageRestriction: "12+ (consult pharmacist for children under 12).",
  },
  {
    name: "Ibuprofen 200mg Tablets",
    icon: "💊",
    symptoms: ["headache", "fever", "pain", "inflammation", "body ache", "cramps"],
    directions: "Take 1-2 tablets every 4-6 hours with food.",
    dosage: "Max 6 tablets (1200mg) per 24 hours.",
    warnings: "Avoid if pregnant, have ulcers, or kidney issues.",
    ageRestriction: "12+.",
  },
  {
    name: "Loratadine 10mg Tablets",
    icon: "🤧",
    symptoms: ["allergy", "runny nose", "sneezing", "itchy eyes", "hives"],
    directions: "Take 1 tablet once daily.",
    dosage: "Max 1 tablet (10mg) per 24 hours.",
    warnings: "Non-drowsy, but stop if rash worsens.",
    ageRestriction: "6+.",
  },
  {
    name: "Diphenhydramine 25mg Tablets",
    icon: "🤧",
    symptoms: ["allergy", "itching", "hives", "mild insomnia"],
    directions: "Take 1-2 tablets every 4-6 hours.",
    dosage: "Max 6 tablets (150mg) per 24 hours.",
    warnings: "Causes drowsiness. Do not drive after taking.",
    ageRestriction: "12+.",
  },
  {
    name: "Guaifenesin Cough Syrup",
    icon: "🍯",
    symptoms: ["cough", "chest congestion", "mucus"],
    directions: "Take 10-20mL every 4 hours with water.",
    dosage: "Max 6 doses per 24 hours.",
    warnings: "Drink plenty of fluids while taking.",
    ageRestriction: "12+.",
  },
  {
    name: "Antacid Chewable Tablets",
    icon: "🌿",
    symptoms: ["heartburn", "indigestion", "upset stomach"],
    directions: "Chew 2-4 tablets as symptoms occur.",
    dosage: "Max 16 tablets per 24 hours.",
    warnings: "Do not use for more than 2 weeks without consulting a doctor.",
    ageRestriction: "12+.",
  },
  {
    name: "Hydrocortisone 1% Cream",
    icon: "🩹",
    symptoms: ["rash", "itching", "insect bite", "skin irritation"],
    directions: "Apply a thin layer to affected area up to 3-4 times daily.",
    dosage: "Do not use for more than 7 days without consulting a doctor.",
    warnings: "For external use only. Avoid eyes and broken skin.",
    ageRestriction: "2+.",
  },
];
